### ISSUE TITLE
UglifyJS2 doesn't work on template literals

### ISSUE THREAD

**Issue by pensierinmusica** [shkuznetsov/gulp-minify-inline#15] opened 2017-02-07 04:57 UTC
See https://github.com/mishoo/UglifyJS2/issues/1401

**Comment by shtalinberg** [comment] 2017-03-07 13:04
workaround
http://stackoverflow.com/questions/34398338/uglification-failed-unexpected-character

**Comment by shkuznetsov** [comment] 2017-06-26 11:36
Closing as a duplicate of #18

**Closed by shkuznetsov** 2017-06-26 11:36 UTC
