### ISSUE TITLE
Unminfies my html

### ISSUE THREAD

**Issue by micahblu** [shkuznetsov/gulp-minify-inline#9] opened 2016-02-10 22:26 UTC
Thanks for the plugin. The issue I have is that I'm feeding in html that is already minified though has some inline css and javascript which is not. The plugin minifies the inline css and javascript but unminfies the html! Any ideas on why that's happening? Thanks

**Comment by shkuznetsov** [comment] 2016-02-11 12:13
That is a very unusually sounding issue! I use this plugin myself a lot with pre-minified HTML, so do quite a few people who use it too, but I haven't yet heard of / seen this effect.

Could you please supply me with a reproduction package including your gulpfile and the affected HTML -- I'll be happy to trace this down and fix.

**Comment by shkuznetsov** [comment] 2016-04-16 10:13
Sorry closing that due to no communication, please re-open and supply additional information if the issue persists.

**Closed by shkuznetsov** 2016-04-16 10:13 UTC
